# Rustfmt configuration for Music Assistant Desktop App
# https://rust-lang.github.io/rustfmt/

edition = "2021"
max_width = 100
tab_spaces = 4
use_small_heuristics = "Default"
newline_style = "Auto"
